### ISSUE TITLE
After 5-10K insertions the process becomes very slow and not parallel.  

### ISSUE THREAD

**Issue by a-artak** [bd2kccd/py-causal#13]
Hi,

I am running py-causal and also tested cmd line version of java for about 3K time series. After a little while it starts inserting, at first it seems running parallel and fast but after 5-10K inserstions it becomes extremly slow. 
I don't know what is the issue, but it seems either
1. network becomes big and becomes extremely slow 
2. Or there is some bug that prevents from parallel run. 

I have checked both CPU usage and Memory, both are ok and not maxed out. 

I am running on Mac Book Pro i7 16G RAM.

Thanks
Artak

**Comment by espinoj** [comment]
Artak,

Is it possible that you can send us the command line parameters and data (anonymized if sensitive) so we can replicate and run a profile on the analysis.  This would allow us to see where the bottleneck is and hopefully address it.

- Jeremy
juest4@pitt.edu

**Comment by a-artak** [comment]
Hi Jeremy,

here is the running code
fgs = s.fgs(df, penaltydiscount = 4, depth = 3, heuristicSpeedup = True,
numofthreads = 8, verbose = True)

Please download data from
https://s3-ap-southeast-2.amazonaws.com/amirbekyan/ts_day.tar.gz

Thanks
Artak

**Comment by a-artak** [comment]
I have filled missing values. 
https://s3-ap-southeast-2.amazonaws.com/amirbekyan/ts_test.tar.gz
try downloading this one please.
