### ISSUE TITLE
JVM size?

### ISSUE THREAD

**Issue by harryhoch** [bd2kccd/py-causal#14]
Just got an out of memory error on a moderately sized dataset. ~ 250 rows, 17K columns. Is there any way to adjust the memory that pycausal allots for the JVM?

**Comment by chirayukong** [comment]
Indeed, you could. When you start the pycausal VM. You can specify the heap size of VM with the **_java_max_heap_size_** variable as shown belows:

```
def start_vm(java_max_heap_size = None):
    tetrad_libdir = os.path.join(os.path.dirname(__file__), 'lib')

    for l in glob.glob(tetrad_libdir + os.sep + "*.jar"):
        javabridge.JARS.append(str(l))
            
    javabridge.start_vm(run_headless=True, max_heap_size = java_max_heap_size)
    javabridge.attach()
```
