### ISSUE TITLE
Add ccd-helpdesk as member

### ISSUE THREAD

**Issue by ccd-helpdesk** [bd2kccd/py-causal#19]
Hi,

This is Ruben in behalf the CCD-helpdesk. Can you add this github user:  "ccd-helpdesk"  as members of the   bdk2kccd/py-causal repository. We just want to be notified in our gmail account about issues we can response to, for example, problems formatting data, interpretation of algorithm output, theoretical questions about causal search, etc. 

Thanks,

Ruben

**Comment by chirayukong** [comment]
Ruben,

The "ccd-helpdesk" user was added to py-causal and r-causal repos.

Regards,

Kong

**Comment by ccd-helpdesk** [comment]
Thanks Kong,

Ruben
