### ISSUE TITLE
need to install javabridge

### ISSUE THREAD

**Issue by harryhoch** [bd2kccd/py-causal#2]
should mention javabridge as a dependency

**Comment by harryhoch** [comment]
conda install -c https://conda.anaconda.org/auto javabridge

**Comment by chirayukong** [comment]
- Prerequisites Installation Added to README
- I use this one to install javabridge:
  conda install python-javabridge

**Comment by harryhoch** [comment]
this doesn't quite work on OS X 

I had to run anaconda search -t conda python-javabridge and then
     conda install --channel https://conda.anaconda.org/david_baddeley python-javabridge
