### ISSUE TITLE
Issue with background knowledge

### ISSUE THREAD

**Issue by bja43** [bd2kccd/py-causal#25]
I cannot get background knowledge to work without error.  I get an error on line 31 in pycausal/prior.py:

    prior = javabridge.JClassWrapper('edu.cmu.tetrad.data.Knowledge2')()

When the above line is called I get the following error (in quotes):

"  File "/usr/local/lib/python2.7/dist-packages/pycausal/prior.py", line 31, in knowledge
    prior = javabridge.JClassWrapper('edu.cmu.tetrad.data.Knowledge2')()
  File "/usr/local/lib/python2.7/dist-packages/javabridge/wrappers.py", line 182, in __init__
    STATIC = J.get_static_field("java/lang/reflect/Modifier", "STATIC", "I")
  File "/usr/local/lib/python2.7/dist-packages/javabridge/jutil.py", line 979, in get_static_field
    klass = env.find_class(class_name)
AttributeError: 'NoneType' object has no attribute 'find_class'   "

**Comment by chirayukong** [comment]
The conda repo is not up-to-date. Could you re-build and install the py-causal from the github source code? I'm updating the conda one.

**Comment by bja43** [comment]
I was not using anaconda when I got the above error.  The above error came after installing pycausal with:

pip install git+git://github.com/bd2kccd/py-causal

**Comment by chirayukong** [comment]
It seems to be the javabridge problem with a tetrad-cmd jar. I can't emulate this problem on the mac and on the docker. They both work fine.

**Comment by bja43** [comment]
I am using Linux.  Perhaps therein lies the problem?

**Comment by chirayukong** [comment]
On the docker container, the os is Debian as well. Which java are you using? I use java 8.

**Comment by tritas** [comment]
Having the same issue, with the same setup. Would you happen to have found a solution @bja43?
