### ISSUE TITLE
Issue with running FGES

### ISSUE THREAD

**Issue by reck0ner** [bd2kccd/py-causal#42]
Hi I am using Ubuntu and I installed using pip, however I get the following error:

JavaException                             Traceback (most recent call last)
<ipython-input-7-c8d788ca281b> in <module>()
      1 from pycausal import search as s
----> 2 fges = s.fges(df,penaltyDiscount = 2, maxDegree = -1, faithfulnessAssumed = True, verbose = True, priorKnowledge = prior)

/usr/local/lib/python2.7/dist-packages/pycausal/search.pyc in __init__(self, df, penaltyDiscount, maxDegree, faithfulnessAssumed, verbose, priorKnowledge, numBootstrap, ensembleMethod)
    454             score.setPenaltyDiscount(penaltyDiscount) # set to 2 if variable# <= 50 otherwise set it to 4
    455 
--> 456             fges = javabridge.JClassWrapper('edu.cmu.tetrad.search.Fges')(score)
    457             fges.setMaxDegree(maxDegree)
    458             fges.setNumPatternsToStore(0)

/usr/local/lib/python2.7/dist-packages/javabridge/wrappers.pyc in __call__(self, *args)
    349             args_sig = "".join(map(sig, params))
    350             msig = "(%s)V" % (args_sig)
--> 351             result =  J.make_instance(self.cname, msig, *cargs)
    352             result = JWrapper(result)
    353             return result

/usr/local/lib/python2.7/dist-packages/javabridge/jutil.pyc in make_instance(class_name, sig, *args)
   1726     jexception = get_env().exception_occurred()
   1727     if jexception is not None:
-> 1728         raise JavaException(jexception)
   1729     return result
   1730 

JavaException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created

**Comment by chirayukong** [comment]
I don't know what is going on in your Ubuntu. I think it is about Javabridge version conflicts. Try to re-install them:

`pip install -U javabridge`

But in the mean while, could you try to run this by calling the Tetrad-lib jar directly? Below are examples how to run them on Javabridge:

- [FGES with continuous dataset](https://github.com/bd2kccd/py-causal/blob/development/example/javabridge/Python-Javabridge%20calling%20directly%20Py-Causal%20FGES%20Continuous%20Example.ipynb)
- [FGES with discrete dataset](https://github.com/bd2kccd/py-causal/blob/development/example/javabridge/Python-Javabridge%20calling%20directly%20Py-Causal%20FGES%20Discrete%20Example.ipynb)
- [FGES with mixed dataset](https://github.com/bd2kccd/py-causal/blob/development/example/javabridge/Python-Javabridge%20calling%20directly%20Py-Causal%20FGES%20Mixed%20Example.ipynb)

**Comment by rumanalakdawala** [comment]
Well I did re install javabridge many times. It doesn't help.
