### ISSUE TITLE
loadDiscreteData doesn't work on Python 3

### ISSUE THREAD

**Issue by chirayukong** [bd2kccd/py-causal#54]
Need to debug it!

**Comment by chirayukong** [comment]
Could you try 'pip install git+git://github.com/bd2kccd/py-causal' instead? The code in the conda repo is not up to date.

**Comment by chirayukong** [comment]
The conda repo is now updated to v1.1.0. It should be good to install it with `conda install -c https://conda.anaconda.org/chirayu pycausal`.

**Comment by firmai** [comment]
This might be an unrelated issue, but I am getting this now.

[cid:42b8ec85-0fe1-4409-9a7f-424952956e70]

Regards
________________________________

**Comment by chirayukong** [comment]
Fixed!
