### ISSUE TITLE
Results changed in v1.1.1

### ISSUE THREAD

**Issue by ikeuchy** [bd2kccd/py-causal#77]
Has the usage changed in v1.1.1?

When changed from v1.1.0 to v1.1.1, the result of the following example changed:
https://github.com/bd2kccd/py-causal/blob/development/example/py-causal%20-%20Bootstrapping%20GFCI%20Continuous%20in%20Action.ipynb

### The result of `tetrad.getEdges()` in **v1.1.0**:
['AmountDonated o-o Sympathy [AmountDonated o-o Sympathy]:0.4000;[no edge]:0.6000;',
 'Sympathy o-> Impact [Impact <-o Sympathy]:1.0000;',
 'Sympathy --> TangibilityCondition [Sympathy --> TangibilityCondition nl pd]:1.0000; nl pd']

### The result of `tetrad.getEdges()` in **v1.1.1**:
['AmountDonated o-o Sympathy',
 'Sympathy o-> Impact',
 'Sympathy --> TangibilityCondition']

**Comment by chirayukong** [comment]
We changed the parameters; so, you can not only do bootstrapping but also resample without replacement. Plus, you can specify the size of resamples.
**v1.1.0**
bootstrapSampleSize = 5,
bootstrapEnsemble = 0
**v1.1.1**
numberResampling = 5,
resampleSize = 94, # new parameter
resamplingWithReplacement = True, # new parameter, (default value: True)
resamplingEnsemble = 0

**Note:** I need to update examples, though.

**Comment by ikeuchy** [comment]
Thank you for answering. I will try it.
