### ISSUE TITLE
Different output compared to Tetrad GUI

### ISSUE THREAD

**Issue by chris-tran-16** [bd2kccd/py-causal#83]
I'm getting different graphs compared to using the Tetrad-GUI using the same algorithm on the example files (FOFC Continuous), when using the same parameters (alpha=0.01 all else False).

![image](https://user-images.githubusercontent.com/23442836/60034573-96156980-9670-11e9-8a18-11df3a584239.png)
![image](https://user-images.githubusercontent.com/23442836/60034593-a0376800-9670-11e9-9076-12d4a91fc3c2.png)

This also occurs with my dataset where I get 5 latent variables on the GUI and 3 using python.

**Comment by chirayukong** [comment]
What version of your Tetrad?

**Comment by chris-tran-16** [comment]
> What version of your Tetrad?

It was 6.4.0. But I checked and downloaded the 6.6.0 version and still get the same result as the second picture.

**Comment by chirayukong** [comment]
The Tetrad-lib is updated in the core repo but not in the py-causal. I'll let you know when it is up to date.

**Comment by chirayukong** [comment]
The updated library and the python codes should produce the same result. Please update the py-causal base code from the development branch.

**Comment by chris-tran-16** [comment]
This example is working the same now. Thanks!
